import { z } from "zod";

export const auditTrailReadSchema = z.object({
  id: z.string(),
  run_id: z.string(),
  batch_id: z.string(),
  strategy_snapshot: z.record(z.string(), z.unknown()),
  profile_snapshot: z.record(z.string(), z.unknown()),
  provider_symbol: z.string(),
  timeframe: z.string(),
  period_start: z.string(),
  period_end: z.string().nullable(),
  direction_mode: z.string(),
  run_kind: z.string(),
  credit_max: z.number().int().nullable(),
  credit_balance: z.number().int().nullable(),
  credit_remaining: z.number().int().nullable(),
  credit_tier: z.string().nullable(),
  credit_reset: z.string().nullable(),
  credit_checked_at: z.string().nullable(),
  agent_runtime: z.string().nullable(),
  model: z.string().nullable(),
  prompt_version: z.string().nullable(),
  executor_version: z.string().nullable(),
  mcp_action: z.string().nullable(),
  external_job_id: z.string().nullable(),
  external_result_id: z.string().nullable(),
  engine_info: z.string().nullable(),
  data_freshness: z.string().nullable(),
  report_link: z.string().nullable(),
  report_available: z.boolean(),
  raw_response: z.record(z.string(), z.unknown()).nullable(),
  raw_response_available: z.boolean(),
  created_at: z.string(),
  started_at: z.string().nullable(),
  ended_at: z.string().nullable(),
  finalized_at: z.string().nullable(),
});

export type AuditTrailRead = z.infer<typeof auditTrailReadSchema>;
